import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import Menu from '@/components/Menu'
import Modal from '@/components/Modal'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>StyleShare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Menu />
      <Modal />
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB39HZG9yQjdwuScfStq7ErWjkYf2h6O44&libraries=places&callback=initMap"async></script>
    </>
  )
}
