import { useState } from 'react';
import {sum as addition} from './math.utils';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css'
import Head from 'next/head'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export default function profilePage() {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1>PROFILE</h1>
    </>
  )
}
