import { useState } from 'react'
import { sum as addition } from './math.utils'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Head from 'next/head'
import Header from '@/components/Header'
import Profile from '@/components/Profile'
import Modal from '@/components/Modal'

const inter = Inter({ subsets: ['latin'] })

function profilePage({ name, image }) {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Profile user={name} image={image} />
      <Modal />
    </>
  )
}

export async function getServerSideProps(context) {
  const { query } = context
  const { name, image } = query
  return {
    props: {
      name: name || null,
      image: image || null,
    },
  }
}

export default profilePage
